[package]
name = "rraw"
version = "0.0.3"
authors = ["Wyatt J Herkamp <wherkamp@kingtux.me>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/wherkamp/rraw"
keywords = ["Reddit", "Async"]
categories = ["api-bindings"]
description = "An async Rust Reddit API Wrapper"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.73"
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.52"
base64 = "0.13.0"
log = "0.4.14"
thiserror = "1.0.30"
[dependencies.reqwest]
version = "0.11.8"
features = ["json"]

[dev-dependencies]
dotenv = "0.15.0"
